# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Invenia Blog
tagline:          'Electricity Grids, Julia, and Machine Learning'
description:      'Blogging About Electricity Grids, Julia, and Machine Learning'
url:              https://invenia-blog.github.io/
baseurl:          /invenia-blog.github.io/

author:
  name:           'Invenia'
  url:            https://www.invenia.ca/

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/invenia-blog/invenia-blog.github.io

avatar: https://www.invenia.ca/wp-content/uploads/favicon.png

plugins: [jekyll-paginate]
